format = """
$directory\
$git_branch\
$git_status\
$git_state\
$mise\
$nodejs\
$python\
$rust\
$golang\
$java\
$aws\
$cmd_duration\
$character"""
# $gcloud\
# $docker_context\
# $package\

add_newline = false

[directory]
format = "[ $path ]($style)"
style = "bg:#121211 fg:#8c816b"

repo_root_format = "[ $before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)[ ]($style)"
before_repo_root_style = "bg:#121211 fg:#8c816b"
repo_root_style = "bg:#121211 fg:#d5c4a1"
read_only_style = "bg:#121211 fg:#52261a"                                                                                                                # maybe needs to change
truncate_to_repo = true

[character]
success_symbol = "[%](240)"
error_symbol = "[%](red)"
format = " $symbol "

[git_branch]
format = "[ $symbol$branch]($style)"
style = "bg:#21201e fg:#8c816b"
symbol = ""
truncation_length = 25
truncation_symbol = "‚Ä¶"

[git_status]
format = '[$untracked$modified$conflicted$deleted$renamed$staged$ahead_behind ]($style)'
style = "bg:#21201e fg:#8c816b"
ahead = "‚Üë${count}"
behind = "‚Üì${count}"
diverged = "‚Üë${ahead_count}‚Üì${behind_count}"
conflicted = "!"
untracked = "*"
modified = "*"
staged = "+"
renamed = "¬ª"
deleted = "x"

[git_state]
format = '([$state( $progress_current/$progress_total)]($style))'
style = "fg:#8c816b"

[nodejs]
format = " [$symbol($version)]($style)"
style = "fg:#5c574d"
symbol = "node "
detect_extensions = [""]

[python]
format = " [$symbol$pyenv_prefix($version)($virtualenv)]($style)"
style = "fg:#5c574d"
symbol = "py "
detect_files = ['.python-version', 'pyproject.toml']
detect_extensions = [""]

[rust]
format = " [$symbol($version)]($style)"
style = "fg:#5c574d"
symbol = "rust "
detect_extensions = [""]

[golang]
format = " [$symbol($version)]($style)"
style = "fg:#5c574d"
symbol = "go "
detect_extensions = [""]

[java]
format = " [$symbol($version)]($style)"
style = "fg:#5c574d"
symbol = "java "
detect_extensions = [""]

# [docker_context]
# format = " [$symbol$context]($style)"
# style = "fg:#8c816b"
# symbol = " "

[aws]
format = " [$symbol($profile)(\\($region\\))(\\[$duration\\])]($style)"
style = "fg:#8c816b"
symbol = "aws "

# [gcloud]
# format = " [$symbol$account(@$domain)(\\($region\\))]($style)"
# style = "fg:#8c816b"
# symbol = "‚òÅÔ∏è "

# [package]
# format = " [$symbol$version]($style)"
# style = "fg:#5c574d"
# symbol = "üì¶ "

[cmd_duration]
format = " [$duration]($style)"
style = "fg:#8c816b"
min_time = 2000

[time]
format = " [$time]($style)"
style = "fg:#8c816b"
disabled = false
